import { notFound } from 'next/navigation'
import { PageContainer } from '@/components/page-container'
import { BreadcrumbSetter } from '@/components/breadcrumb-setter'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { getEventTypeWithRelationsBySlug } from '@/lib/actions/event-types'
import { checkSettingsAccess } from '@/lib/auth/permissions'
import { getTranslations } from 'next-intl/server'
import { Info, ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { ScriptsListClient } from './scripts-list-client'

interface PageProps {
  params: Promise<{ slug: string }>
}

export default async function ScriptsPage({ params }: PageProps) {
  // Check admin permissions (redirects if not authorized)
  await checkSettingsAccess()

  const { slug } = await params
  const t = await getTranslations()

  // Fetch event type with scripts
  const eventType = await getEventTypeWithRelationsBySlug(slug)

  if (!eventType) {
    notFound()
  }

  // Determine parent settings page based on system_type
  const parentPath =
    eventType.system_type === 'mass-liturgy'
      ? '/settings/mass-liturgies'
      : eventType.system_type === 'special-liturgy'
        ? '/settings/special-liturgies'
        : '/settings/events'

  const parentLabel =
    eventType.system_type === 'mass-liturgy'
      ? t('nav.masses')
      : eventType.system_type === 'special-liturgy'
        ? t('nav.specialLiturgies')
        : t('nav.events')

  const breadcrumbs = [
    { label: t('nav.dashboard'), href: '/dashboard' },
    { label: t('nav.settings'), href: '/settings' },
    { label: parentLabel, href: parentPath },
    { label: eventType.name, href: `/settings/event-types/${slug}` },
    { label: t('eventType.scripts.title') },
  ]

  // Check if this is a special liturgy
  const isSpecialLiturgy = eventType.system_type === 'special-liturgy'

  return (
    <PageContainer
      title={`${eventType.name} - ${t('eventType.scripts.title')}`}
      description={
        isSpecialLiturgy
          ? t('eventType.scripts.description')
          : undefined
      }
    >
      <BreadcrumbSetter breadcrumbs={breadcrumbs} />

      <div className="space-y-6">
        {/* Back button */}
        <div>
          <Button variant="outline" asChild>
            <Link href={`/settings/event-types/${slug}`}>
              <ArrowLeft className="w-4 h-4 mr-2" />
              {t('common.back')}
            </Link>
          </Button>
        </div>

        {/* Special Liturgy: Show full script builder */}
        {isSpecialLiturgy && (
          <ScriptsListClient eventType={eventType} initialScripts={eventType.scripts || []} />
        )}

        {/* Mass/Event: Show auto-generation message */}
        {!isSpecialLiturgy && (
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription>
              {t('eventType.scripts.autoGeneratedMessage', { eventTypeName: eventType.name })}
            </AlertDescription>
          </Alert>
        )}
      </div>
    </PageContainer>
  )
}
