import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import { createRequire } from "module";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const require = createRequire(import.meta.url);

// Local ESLint plugin for project-specific rules
const localPlugin = require("./eslint-plugins/index.js");

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'out/**',
      '.vercel/**',
      'playwright-report/**',
      'test-results/**',
      'dist/**',
      'scripts/**',
      '**/*.md',
      'docs/**',
      'next-env.d.ts', // Auto-generated by Next.js
      'eslint-plugins/**', // Don't lint the ESLint plugin itself
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    plugins: {
      'local': localPlugin,
    },
    rules: {
      // Allow 'any' in type definitions, generic components, and API routes where flexibility is needed
      '@typescript-eslint/no-explicit-any': 'off',
      // Allow require imports in specific cases (petition templates use dynamic requires)
      '@typescript-eslint/no-require-imports': 'off',
      // Enforce component wrapper usage for consistent styling
      'local/no-direct-ui-imports': 'error',
    },
  },
  // Allow wrapper components to import from ui/
  // Add new wrapper files here as they're created
  {
    files: [
      'src/components/content-card.tsx',
    ],
    rules: {
      'local/no-direct-ui-imports': 'off',
    },
  },
];

export default eslintConfig;
